MOM Chanel Project: org.swallow_labs.model.Capsule.Capsule Class Reference
org.swallow_labs.model.Capsule.Capsule Class Reference
Public Member Functions
def __init__
def get_id_capsule (self)
def get_tts (self)
def get_ACK (self)
def get_id_sender (self)
def get_id_receiver (self)
def get_priority (self)
def get_sort (self)
def get_payload (self)
def get_status_capsule (self)
def get_type (self)
def get_sending_date (self)
def get_receiving_date (self)
def set_id_receiver (self, id_receiver)
def set_priority (self, priority)
def set_payload (self, payload)
def set_sending_date (self, sending_date)
def set_yes_ACK (self)
def set_tts (self, tts)
def set_receiving_date (self, receiving_date)
def set_status_capsule (self, status_capsule)
def set_type (self, type)
def set_sort (self, sort)
def print_capsule (self)
Static Public Member Functions
def capsule_id ()
Public Attributes
id_capsule
id_sender
status_capsule
type
sending_date
ACK
id_receiver
priority
payload
tts
receiving_date
sort
Static Public Attributes
int cpt_capsule = 0
tuple my_logger = LoggerAdapter(Parser().get_capsule_log_param())
Private Attributes
__dict__
Detailed Description
    Class creating a capsule object:
    G{classtree}
    DESCRIPTION
    ===========
    Create a capsule
    RETURN
    ======
    Return a capsule
    @param id_sender:    Sender ID
    @param j:    Json object
    @type id_sender: int
    @type j: String
    @ivar self.id_sender:    Sender ID
    @ivar self.id_receiver:    Receiver ID
    @ivar self.priority:    Capsule priority
    @ivar self.payload:    Message wanted to send
    @ivar self.type:    Message type (PAYLOAD, READY, END)
    @ivar self.sending_date:    Capsule sending date
    @ivar self.receiving_date:    Capsule receiving date
    @ivar self.status_capsule:    Capsule status(YES if read it and NO if still not read it by the broker)
    @ivar self.tts      Capsule time taking to send
    @ivar self.ACK      Capsule ACK(YES/NO if YES it an ACK or is simple message)
Definition at line 6 of file Capsule.py.
Constructor & Destructor Documentation
def org.swallow_labs.model.Capsule.Capsule.__init__ (self, id_sender = None, type = None, j = None)
    :
Definition at line 44 of file Capsule.py.
     def __init__(self, id_sender=None, type=None, j=None):
         """
             :
         """
         if j is None:
             self.id_capsule = str(Capsule.capsule_id()).zfill(10)
             self.id_sender = id_sender
             # By default the status of the capsule is not yet read by the broker
             self.status_capsule = "NO"
             self.type = type
             # add to the capsule, date of sending
             self.sending_date = time.ctime()
             Capsule.my_logger.log_init_capsule(self.id_capsule, self.get_id_sender(), self.get_type())
             self.ACK= "NO"
         else:
             self.__dict__ = json.loads(j)
Member Function Documentation
def org.swallow_labs.model.Capsule.Capsule.capsule_id () static
Definition at line 65 of file Capsule.py.
     def capsule_id():
         if Capsule.cpt_capsule == 9999999999:
             return 1
         Capsule.cpt_capsule += 1
         return Capsule.cpt_capsule
def org.swallow_labs.model.Capsule.Capsule.get_ACK (self)
DESCRIPTION
===========
Method providing a way to get the capsule ACK
Definition at line 94 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.ACK.
Referenced by org.swallow_labs.model.Capsule.Capsule.print_capsule().
     def get_ACK(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to get the capsule ACK
         """
         return self.ACK
def org.swallow_labs.model.Capsule.Capsule.get_id_capsule (self)
DESCRIPTION
===========
Method providing a way to get the capsule ID
Definition at line 74 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.id_capsule.
Referenced by org.swallow_labs.model.Capsule.Capsule.print_capsule().
     def get_id_capsule(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to get the capsule ID
         """
         return self.id_capsule
def org.swallow_labs.model.Capsule.Capsule.get_id_receiver (self)
DESCRIPTION
===========
Method providing a way to get the receiver ID
Definition at line 113 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.id_receiver.
Referenced by org.swallow_labs.model.Capsule.Capsule.print_capsule().
     def get_id_receiver(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to get the receiver ID
         """
         return self.id_receiver
def org.swallow_labs.model.Capsule.Capsule.get_id_sender (self)
DESCRIPTION
===========
Method providing a way to get the sender ID
Definition at line 103 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.id_sender.
Referenced by org.swallow_labs.model.Capsule.Capsule.print_capsule().
     def get_id_sender(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to get the sender ID
         """
         return self.id_sender
def org.swallow_labs.model.Capsule.Capsule.get_payload (self)
DESCRIPTION
===========
Method providing a way to get the payload
Definition at line 142 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.payload.
Referenced by org.swallow_labs.model.Capsule.Capsule.print_capsule().
     def get_payload(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to get the payload
         """
         return self.payload
def org.swallow_labs.model.Capsule.Capsule.get_priority (self)
DESCRIPTION
===========
Method providing a way to get the capsule priority
Definition at line 123 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.priority.
Referenced by org.swallow_labs.model.Capsule.Capsule.print_capsule().
     def get_priority(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to get the capsule priority
         """
         return self.priority
def org.swallow_labs.model.Capsule.Capsule.get_receiving_date (self)
DESCRIPTION
===========
Method providing a way to get the time of receiving of the capsule
Definition at line 182 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.receiving_date.
     def get_receiving_date(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to get the time of receiving of the capsule
         """
         return self.receiving_date
def org.swallow_labs.model.Capsule.Capsule.get_sending_date (self)
DESCRIPTION
===========
Method providing a way to get the time of sending of the capsule
Definition at line 172 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.sending_date.
Referenced by org.swallow_labs.model.Capsule.Capsule.print_capsule().
     def get_sending_date(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to get the time of sending of the capsule
         """
         return self.sending_date
def org.swallow_labs.model.Capsule.Capsule.get_sort (self)
DESCRIPTION
===========
Method providing a way to get the capsule sort
Definition at line 133 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.sort.
Referenced by org.swallow_labs.model.Capsule.Capsule.print_capsule().
     def get_sort(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to get the capsule sort
         """
         return self.sort
def org.swallow_labs.model.Capsule.Capsule.get_status_capsule (self)
DESCRIPTION
===========
Method providing a way to get the capsule status
Definition at line 152 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.status_capsule.
Referenced by org.swallow_labs.model.Capsule.Capsule.print_capsule().
     def get_status_capsule(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to get the capsule status
         """
         return self.status_capsule
def org.swallow_labs.model.Capsule.Capsule.get_tts (self)
DESCRIPTION
===========
Method providing a way to get the capsule tts
Definition at line 84 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.tts.
     def get_tts(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to get the capsule tts
         """
         return self.tts
def org.swallow_labs.model.Capsule.Capsule.get_type (self)
DESCRIPTION
===========
Method providing a way to get the capsule type
Definition at line 162 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.type.
Referenced by org.swallow_labs.model.Capsule.Capsule.print_capsule().
     def get_type(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to get the capsule type
         """
         return self.type
def org.swallow_labs.model.Capsule.Capsule.print_capsule (self)
DESCRIPTION
===========
Method Print Capsule
Definition at line 294 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.get_ACK(), org.swallow_labs.model.Capsule.Capsule.get_id_capsule(), org.swallow_labs.model.Capsule.Capsule.get_id_receiver(), org.swallow_labs.model.Capsule.Capsule.get_id_sender(), org.swallow_labs.model.Capsule.Capsule.get_payload(), org.swallow_labs.model.Capsule.Capsule.get_priority(), org.swallow_labs.model.Capsule.Capsule.get_sending_date(), org.swallow_labs.model.Capsule.Capsule.get_sort(), org.swallow_labs.model.Capsule.Capsule.get_status_capsule(), and org.swallow_labs.model.Capsule.Capsule.get_type().
     def print_capsule(self):
         """
         DESCRIPTION
         ===========
         Method Print Capsule
         """
         return('Capsule ID: {}, Priority : {}, ID sender : {}, ID receiver : {}, Capsule Status : {},'
               ' Capsule type : {}, Payload : {}, Sending date : {}, Capsule Sort : {}, Capsule ACK : {}'.format(self.get_id_capsule(),
                                                                                                 self.get_priority(),
                                                                                                 self.get_id_sender(),
                                                                                                 self.get_id_receiver(),
                                                                                                 self.get_status_capsule(),
                                                                                                 self.get_type(),
                                                                                                 self.get_payload(),
                                                                                                 self.get_sending_date(),
                                                                                                 self.get_sort(),
                                                                                                 self.get_ACK()
                                                                                                 ))
def org.swallow_labs.model.Capsule.Capsule.set_id_receiver (self, id_receiver)
DESCRIPTION
===========
Method providing a way to set the receiver ID
Definition at line 194 of file Capsule.py.
     def set_id_receiver(self, id_receiver):
         """
         DESCRIPTION
         ===========
         Method providing a way to set the receiver ID
         """
         self.id_receiver = id_receiver
def org.swallow_labs.model.Capsule.Capsule.set_payload (self, payload)
DESCRIPTION
===========
Method providing a way to set the payload
Definition at line 214 of file Capsule.py.
     def set_payload(self, payload):
         """
         DESCRIPTION
         ===========
         Method providing a way to set the payload
         """
         self.payload = payload
def org.swallow_labs.model.Capsule.Capsule.set_priority (self, priority)
DESCRIPTION
===========
Method providing a way to set the capsule priority
Definition at line 204 of file Capsule.py.
     def set_priority(self, priority):
         """
         DESCRIPTION
         ===========
         Method providing a way to set the capsule priority
         """
         self.priority = priority
def org.swallow_labs.model.Capsule.Capsule.set_receiving_date (self, receiving_date)
DESCRIPTION
===========
Method providing a way to set the receiving date
Definition at line 254 of file Capsule.py.
     def set_receiving_date(self, receiving_date):
         """
         DESCRIPTION
         ===========
         Method providing a way to set the receiving date
         """
         self.receiving_date = receiving_date
def org.swallow_labs.model.Capsule.Capsule.set_sending_date (self, sending_date)
DESCRIPTION
===========
Method providing a way to set the sending date
Definition at line 224 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.sending_date.
     def set_sending_date(self, sending_date):
         """
         DESCRIPTION
         ===========
         Method providing a way to set the sending date
         """
         self.sending_date = sending_date
def org.swallow_labs.model.Capsule.Capsule.set_sort (self, sort)
DESCRIPTION
===========
Method Setting capsule sort
Definition at line 284 of file Capsule.py.
     def set_sort(self, sort):
         """
         DESCRIPTION
         ===========
         Method Setting capsule sort
         """
         self.sort = sort
def org.swallow_labs.model.Capsule.Capsule.set_status_capsule (self, status_capsule)
DESCRIPTION
===========
Method providing a way to set the capsule status
Definition at line 264 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.status_capsule.
     def set_status_capsule(self, status_capsule):
         """
         DESCRIPTION
         ===========
         Method providing a way to set the capsule status
         """
         self.status_capsule = status_capsule
def org.swallow_labs.model.Capsule.Capsule.set_tts (self, tts)
DESCRIPTION
===========
Method providing a way to st the capsule tts
Definition at line 244 of file Capsule.py.
     def set_tts(self,tts):
         """
         DESCRIPTION
         ===========
         Method providing a way to st the capsule tts
         """
         self.tts = tts
def org.swallow_labs.model.Capsule.Capsule.set_type (self, type)
DESCRIPTION
===========
Method Setting capsule type
Definition at line 274 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.type.
     def set_type(self, type):
         """
         DESCRIPTION
         ===========
         Method Setting capsule type
         """
         self.type = type
def org.swallow_labs.model.Capsule.Capsule.set_yes_ACK (self)
DESCRIPTION
===========
Method providing a way to st yes to the capsule ACK
Definition at line 234 of file Capsule.py.
References org.swallow_labs.model.Capsule.Capsule.ACK.
     def set_yes_ACK(self):
         """
         DESCRIPTION
         ===========
         Method providing a way to st yes to the capsule ACK
         """
         self.ACK ="YES"
Member Data Documentation
org.swallow_labs.model.Capsule.Capsule.__dict__ private
Definition at line 61 of file Capsule.py.
org.swallow_labs.model.Capsule.Capsule.ACK
Definition at line 59 of file Capsule.py.
Referenced by org.swallow_labs.model.Capsule.Capsule.get_ACK(), and org.swallow_labs.model.Capsule.Capsule.set_yes_ACK().
int org.swallow_labs.model.Capsule.Capsule.cpt_capsule = 0 static
Definition at line 40 of file Capsule.py.
org.swallow_labs.model.Capsule.Capsule.id_capsule
Definition at line 51 of file Capsule.py.
Referenced by org.swallow_labs.model.CapsuleACK.CapsuleACK.get_id_capsule(), org.swallow_labs.model.Capsule.Capsule.get_id_capsule(), and org.swallow_labs.model.CapsuleACK.CapsuleACK.set_id_capsule().
org.swallow_labs.model.Capsule.Capsule.id_receiver
Definition at line 202 of file Capsule.py.
Referenced by org.swallow_labs.model.Capsule.Capsule.get_id_receiver().
org.swallow_labs.model.Capsule.Capsule.id_sender
Definition at line 52 of file Capsule.py.
Referenced by org.swallow_labs.model.Capsule.Capsule.get_id_sender().
tuple org.swallow_labs.model.Capsule.Capsule.my_logger = LoggerAdapter(Parser().get_capsule_log_param()) static
Definition at line 42 of file Capsule.py.
org.swallow_labs.model.Capsule.Capsule.payload
Definition at line 222 of file Capsule.py.
Referenced by org.swallow_labs.model.Capsule.Capsule.get_payload().
org.swallow_labs.model.Capsule.Capsule.priority
Definition at line 212 of file Capsule.py.
Referenced by org.swallow_labs.model.Capsule.Capsule.get_priority().
org.swallow_labs.model.Capsule.Capsule.receiving_date
Definition at line 262 of file Capsule.py.
Referenced by org.swallow_labs.model.Capsule.Capsule.get_receiving_date().
org.swallow_labs.model.Capsule.Capsule.sending_date
Definition at line 57 of file Capsule.py.
Referenced by org.swallow_labs.model.Capsule.Capsule.get_sending_date(), and org.swallow_labs.model.Capsule.Capsule.set_sending_date().
org.swallow_labs.model.Capsule.Capsule.sort
Definition at line 292 of file Capsule.py.
Referenced by org.swallow_labs.model.Capsule.Capsule.get_sort().
org.swallow_labs.model.Capsule.Capsule.status_capsule
Definition at line 54 of file Capsule.py.
Referenced by org.swallow_labs.model.Capsule.Capsule.get_status_capsule(), and org.swallow_labs.model.Capsule.Capsule.set_status_capsule().
org.swallow_labs.model.Capsule.Capsule.tts
Definition at line 252 of file Capsule.py.
Referenced by org.swallow_labs.model.Capsule.Capsule.get_tts().
org.swallow_labs.model.Capsule.Capsule.type
Definition at line 55 of file Capsule.py.
Referenced by org.swallow_labs.model.Capsule.Capsule.get_type(), and org.swallow_labs.model.Capsule.Capsule.set_type().
The documentation for this class was generated from the following file:
/home/mahdi/PycharmProjects/ChanelProject/org/swallow_labs/model/Capsule.py